// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAvxFtfKTu3TRl9GYe2SilrQgsfMDd4wo',
    appId: '1:708938025607:web:b7ae905bfbacc5b4bfc622',
    messagingSenderId: '708938025607',
    projectId: 'mizan-app-8553c',
    authDomain: 'mizan-app-8553c.firebaseapp.com',
    storageBucket: 'mizan-app-8553c.firebasestorage.app',
    measurementId: 'G-QCQNLNJV3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHBCBPFSLquj6fnyMZCHYLmEASgw4kgY',
    appId: '1:708938025607:android:4cb10c95ba29a638bfc622',
    messagingSenderId: '708938025607',
    projectId: 'mizan-app-8553c',
    storageBucket: 'mizan-app-8553c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaPpBRbrJFKILc1DmHJPj5sGrcNMASmhg',
    appId: '1:708938025607:ios:32bf3be5f7155911bfc622',
    messagingSenderId: '708938025607',
    projectId: 'mizan-app-8553c',
    storageBucket: 'mizan-app-8553c.firebasestorage.app',
    iosBundleId: 'com.example.projectMizan',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaPpBRbrJFKILc1DmHJPj5sGrcNMASmhg',
    appId: '1:708938025607:ios:32bf3be5f7155911bfc622',
    messagingSenderId: '708938025607',
    projectId: 'mizan-app-8553c',
    storageBucket: 'mizan-app-8553c.firebasestorage.app',
    iosBundleId: 'com.example.projectMizan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAvxFtfKTu3TRl9GYe2SilrQgsfMDd4wo',
    appId: '1:708938025607:web:36f7531d5efb354cbfc622',
    messagingSenderId: '708938025607',
    projectId: 'mizan-app-8553c',
    authDomain: 'mizan-app-8553c.firebaseapp.com',
    storageBucket: 'mizan-app-8553c.firebasestorage.app',
    measurementId: 'G-XC7P62123W',
  );
}
